
model: MaskRCNN 
dataset: # dataset name
results_path: "Results/Object Detection/Mask RCNN HPO"

hpo:
  trials: 20
  use_pruning: true
  pruning_n_startup_trials: 5
  pruning_n_warmup_steps: 4
  optuna_database_path: "Results/Object Detection/HPO_Optuna_SQLite_DB.db"

training:
  epochs: 20
  use_early_stopping: true
  early_stopping_patience: 4